config/routes.rb
RegexChallenge::Application.routes.draw do

  get "users/enter_arena" => 'users#enter_arena'

  get "users/exit_arena" => 'users#exit_arena'

  get "site/landing"

  get 'challenges/regex_play' => 'challenges#regex_play'
  post 'challenges/regex_check' => 'challenges#regex_check'

  get 'challenges/output_play' => 'challenges#output_play'
  post 'challenges/output_check' => 'challenges#output_check'

  get 'challenges/friends_list' => 'challenges#friends_list'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  root :to => 'site#landing'

end

app/models/in_string.rb
class InString < ActiveRecord::Base
  attr_accessible :string

  has_many :in_string_regexs
  has_many :regexs, :through => :in_string_regexs

end

app/models/in_string_regex.rb
class InStringRegex < ActiveRecord::Base
  attr_accessible :in_string_id, :regex_id

  belongs_to :in_string
  belongs_to :regex

end

app/models/input_output_string.rb
# == Schema Information
#
# Table name: input_output_strings
#
#  id               :integer          not null, primary key
#  output_string_id :integer
#  input_string_id  :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class InputOutputString < ActiveRecord::Base
  attr_accessible :input_string_id, :output_string_id

  belongs_to :input_string
  belongs_to :output_string

end

app/models/input_string.rb
# == Schema Information
#
# Table name: input_strings
#
#  id               :integer          not null, primary key
#  string           :text
#  output_string_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class InputString < ActiveRecord::Base
  attr_accessible :output_string_id, :string

  has_many :input_output_strings
  has_many :output_strings, :through => :input_output_strings

end

app/models/output_challenge_user_time.rb
class OutputChallengeUserTime < ActiveRecord::Base
  attr_accessible :in_string_regex_id, :time, :user_id
end

app/models/output_string.rb
# == Schema Information
#
# Table name: output_strings
#
#  id              :integer          not null, primary key
#  string          :text
#  input_string_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class OutputString < ActiveRecord::Base
  attr_accessible :input_string_id, :string

  has_one :input_output_string
  has_one :input_string, :through => :input_output_string

end

app/models/regex.rb
class Regex < ActiveRecord::Base
  attr_accessible :expression

  has_one :in_string_regex
  has_one :in_string, :through => :in_string_regex
end

app/models/regex_challenge_user_time.rb
class RegexChallengeUserTime < ActiveRecord::Base
  attr_accessible :input_output_id, :time, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :provider, :uid, :in_arena

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.email = auth['info']['email']
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def regex_play
    @friends = User.where(:in_arena => true)
    @challenge_id = rand(1..InputOutputString.count)
    challenge = InputOutputString.find(@challenge_id)
    @string = InputString.find(challenge.input_string_id).string
    @expected_output = OutputString.find(challenge.output_string_id).string
    @board_times = RegexChallengeUserTime.where(:input_output_id => @challenge_id).order('time')
    @correct = ' '
    @submission = ""
  end

  def regex_check
    @friends = User.where(:in_arena => true)
    @time = params[:time].split(',')
    @submission = params[:submission]
    @string = params[:string]
    @expected_output = params[:expected_output]
    @current_output = @string.scan(eval("/#{@submission}/")).flatten.join(' ')
    if @current_output == @expected_output
      @correct = true
      user_time = @time.pop.to_i + @time.pop.to_i * 60
      RegexChallengeUserTime.create(:user_id => current_user.id,
        :input_output_id => params[:challenge_id],
        :time => user_time)
      @board_times = RegexChallengeUserTime.where(:input_output_id => params[:challenge_id])
    else
      @correct = false
    end
  end

  def output_play
    @friends = User.where(:in_arena => true)
    @challenge_id = rand(1..InStringRegex.count)
    challenge = InStringRegex.find(@challenge_id)
    @input = InString.find(challenge.in_string_id).string
    @regex = Regex.find(challenge.regex_id).expression
    @board_times = OutputChallengeUserTime.where(:in_string_regex_id => @challenge_id)
    @correct = ' '
    @submission = ""
  end

  def output_check
    @friends = User.where(:in_arena => true)
    @time = params[:time].split(',')
    @submission = params[:submission]
    @input = params[:input]
    @regex = params[:regex]
    @correct_output = @input.scan(eval("/#{@regex}/")).flatten.join(' ')
    if @submission == @correct_output
      @correct = true
      user_time = @time.pop.to_i + @time.pop.to_i * 60
      OutputChallengeUserTime.create(:user_id => current_user.id,
        :in_string_regex_id => params[:challenge_id],
        :time => user_time)
      @board_times = OutputChallengeUserTime.where(:in_string_regex_id => params[:challenge_id])
    else
      @correct = false
    end
  end

  def friends_list
    @friends = User.where(:in_arena => true)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) ||
            User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to challenges_regex_play_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def landing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def enter_arena
    User.find(current_user.id).update_attributes(:in_arena => true)
    @friends = User.where(:in_arena => true)
  end

  def exit_arena
    User.find(current_user.id).update_attributes(:in_arena => false)
    @friends = User.where(:in_arena => true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/challenges/_output_results.html.erb
<% if @correct == true %>
    <h2 style="color: red">Great job!</h2>
    <%= link_to 'Next Challenge', challenges_output_play_path, :class => "btn btn-primary"%>
    <% elsif @correct == false %>
    <h2 style="color: red" id="result_msg">Not Quite. Try again.</h2>
<% end %>

app/views/challenges/_regex_results.html.erb
<% if @correct == true %>
  <h2 style="color: red">Great job!</h2>
  <%= link_to 'Next Challenge', challenges_regex_play_path, :class => "btn btn-primary"%>
<% elsif @correct == false %>
  <h2 style="color: red">Not quite. Try again.</h2>
   <h3>Your current output:</h3>
  <div class="span4" style="border:2px solid;float: left; height: 2em; font-size: 20px;background-color: #E2E9E7">
    <%= @current_output %>
  </div>
<% end %>

app/views/challenges/_results.html.erb
<% if @correct == true %>
  <h2 style="color: red">Great job!</h2>
  <%= link_to 'Next Challenge', challenges_regex_play_path, :class => "btn btn-primary"%>
<% elsif @correct == false %>
  <h2 style="color: blue">Not quite.</h2>
   <h3>Your current output:</h3>
  <div class="span4" style="border:2px solid;float: left; height: 2em; font-size: 20px;background-color: #E2E9E7">
    <%= @current_output %>
  </div>
<% end %>

app/views/challenges/friends_list.js.erb
$('#friends_list').html('<%= j render "friends_list" %>');

app/views/challenges/output_check.js.erb
<% if @correct == true  %>
  $('#sinceCompact').countdown('pause');
  $('#submit_next').hide();
  $('#leader_board').html('<%= j render "shared/leader_board" %>');
<% end %>
$('#output_results').html('<%= j render "output_results" %>');
$('#result_msg').fadeOut(3000)

app/views/challenges/output_play.html.erb
<%= notice %>
<% if current_user %>
<%= link_to "Sign out", signout_path %>
<% end %>
<h1 class="page-title">* Output Challenge *</h1>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span6">
      <%= link_to 'Regex Challenge', challenges_regex_play_path, :class => "btn btn-warning" %>

      <%= form_tag challenges_output_check_path, :remote => true do%>
        <h3>Input string:</h3>
        <div class="span5 display-field">
          <%= @input %>
        </div>
        <%= hidden_field_tag :input, @input %>
        <%= hidden_field_tag :challenge_id, @challenge_id %>
        <br><br>
        <h3>Regex:</h3>
        <div class="span5 display-field">
            /<%= @regex %>/
        </div>
        <%= hidden_field_tag :regex, @regex %>
        <br><br>
        <h3> Output: </h3>
        <div class="input-prepend input-append span9">
          <span class="add-on" style="border:2px solid;"><b>"</b></span>
          <input name="submission" value="<%= @submission %>" class="span5" id="appendedPrependedInput" type="text" autocomplete="off" style="font-size: 20px; border:2px solid;">
          <span class="add-on" style="border:2px solid;"><b>"</b></span>
        </div>
        <br><br><br>
        <h4 class="timer-title">Time: </h4><span id="sinceCompact" class="countdown timer">
        </span>
        <div id="submit_next">
          <br>
          <%= button_tag 'Submit Output', :class => "btn btn-primary", :id => "submit" %><br><br>
          <%= link_to 'Next Challenge', challenges_output_play_path, :class => "btn btn-warning", :id => "next_challenge" %>
        </div>
        <%= hidden_field_tag :time, @time, :id => "time"%>
      <% end %>
      <div id="output_results"></div>

    </div>
    <div class="span6">
      <h3 class="span8 arena-title">Looking For A Challenger</h3>
      <div class="span8" id="friends_list" style="height: 200px; border: 2px solid; clear:right; margin-bottom: 3%; background-color: #E2E9E7">
        <%= render 'shared/friends_list' %>
      </div>
      <div style="padding-left: 2%">
      <%= link_to "Update", challenges_friends_list_path, :class => "btn btn-primary update-button", :id => "update_friends", :remote => true%>
      <%= link_to "Enter Arena", users_enter_arena_path, :class => "btn btn-primary arena-button", :id => "enter_arena", :remote => true %>
      <%= link_to "Exit Arena", users_exit_arena_path, :class => "btn btn-primary arena-button", :id => "exit_arena", :style => "display: inline-block; float: left; margin-left: 1%;", :remote => true %>
      </div>
      <h3 class="span8 leader-board-title">Leader Board</h3>
      <div class="span8 leader-board" id="leader_board">
        <%= render 'shared/leader_board' %>
    </div>
  </div>
</div>

app/views/challenges/play.html.erb
<%= form_tag '/challenges/check' do%>
<h3>Input string:</h3>
<div class="span4" style="border:2px solid;float: left; height: 2em; font-size: 20px;padding-left: 20px;background-color: #E2E9E7">
  <%= @string %>
</div>
<%= hidden_field_tag :string, @string %>
<br><br>
<h3>Desired output:</h3>
<div class="span4" style="border:2px solid;float: left; height: 2em; font-size: 20px;background-color: #E2E9E7">
    <%= @expected_output %>
</div>
<%= hidden_field_tag :expected_output, @expected_output %>
<br><br>
<h3> Regex </h3>
<div class="input-prepend input-append span4">
  <span class="add-on">\</span>
  <input name="submission" value="<%= @submission %>"class="span4" id="appendedPrependedInput" type="text" autocomplete="off" style="font-size: 20px;">
  <span class="add-on">\</span>
</div>
<br><br>
<%= button_tag 'Submit Regex', :class => "btn btn-primary" %>

<% end %>

<% if @correct == true %>
  <h2 style="color: red">Great job!</h2>
  <%= link_to 'Next', challenges_play_path, :class => "btn btn-primary"%>
<% elsif @correct == false %>
  <h2 style="color: blue">Not quite.</h2>
   <h3>Your current output:</h3>
  <div class="span4" style="border:2px solid;float: left; height: 2em; font-size: 20px;background-color: #E2E9E7"">
    <%= @current_output %>
  </div>
<% end %>

app/views/challenges/regex_check.js.erb
<% if @correct == true  %>
  $('#sinceCompact').countdown('pause');
  $('#submit_next').hide();
  $('#leader_board').html('<%= j render "shared/leader_board" %>');
<% end %>
$('#regex_results').html('<%= j render "regex_results" %>');
$('#result_msg').fadeOut(3000)

app/views/challenges/regex_play.html.erb
<%= notice %>
<% if current_user %>
<%= link_to "Sign out", signout_path %>
<% end %>
<h1 class="page-title">* Regex Challenge *</h1>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span6">
      <%= link_to 'Output Challenge', challenges_output_play_path, :class => "btn btn-warning" %>

      <%= form_tag challenges_regex_check_path, :remote => true do%>
        <h3>Input string:</h3>
        <div class="span5 display-field">
          <%= @string %>
        </div>
        <%= hidden_field_tag :string, @string %>
        <%= hidden_field_tag :challenge_id, @challenge_id %>
        <br><br>
        <h3>Desired output:</h3>
        <div class="span5 display-field">
            <%= @expected_output %>
        </div>
        <%= hidden_field_tag :expected_output, @expected_output %>
        <br><br>
        <h3> Regex: </h3>
        <div class="input-prepend input-append span9">
          <span class="add-on" style="border:2px solid;"><b>/</b></span>
          <input name="submission" value="<%= @submission %>" class="span5" id="appendedPrependedInput" type="text" autocomplete="off" style="font-size: 20px; border:2px solid;">
          <span class="add-on" style="border:2px solid;"><b>/</b></span>
        </div>
        <br><br><br>
        <div id="timer">
          <h4 class="timer-title">Time: </h4>
          <span id="sinceCompact" class="countdown timer">
          </span>
        </div>
        <div id="submit_next">
          <br>
          <%= button_tag 'Submit Regex', :class => "btn btn-primary", :id => "submit" %>
          <br><br>
          <%= link_to 'Next Challenge', challenges_regex_play_path, :class => "btn btn-warning", :id => "next_challenge" %>
      </div>
        <%= hidden_field_tag :time, @time, :id => "time"%>
      <% end %>
      <div id="regex_results"></div>

    </div>
    <div class="span6">
      <h3 class="span8 arena-title">Looking For A Challenger</h3>
      <div class="span8" id="friends_list" style="height: 200px; border: 2px solid; clear:right; margin-bottom: 3%; background-color: #E2E9E7">
        <%= render 'shared/friends_list' %>
      </div>
      <div style="padding-left: 2%">
      <%= link_to "Update", challenges_friends_list_path, :class => "btn btn-primary update-button", :id => "update_friends", :remote => true%>
      <%= link_to "Enter Arena", users_enter_arena_path, :class => "btn btn-primary arena-button", :id => "enter_arena", :remote => true %>
      <%= link_to "Exit Arena", users_exit_arena_path, :class => "btn btn-primary arena-button", :id => "exit_arena", :remote => true %>
      </div>
      <h3 class="span8 leader-board-title">Leader Board</h3>
      <div class="span8 leader-board" id="leader_board">
        <%= render 'shared/leader_board' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RegexChallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "http://localhost:9292/faye.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_friends_list.html.erb
<table style="width: 100%">
  <% @friends.each do |friend| %>
    <tr>
      <td style="width: 50%;"> <%= friend.name %></td>
      <td> Picture Here </td>
    </tr>
  <% end %>
</table>

app/views/shared/_leader_board.erb
<table style="table-layout: fixed; width: 100%">
  <tr>
    <th></th>
    <th style="width: 52%; text-align: left"> Time </th>
  </tr>
  <% if !@board_times.nil? %>
    <% @board_times.each do |time| %>
      <tr>
        <td style="width: 87%;"> <%= User.find(time.user_id).name %></td>
        <td> <%= time.time/60 %>:<%= sprintf('%02d', time.time%60) %> </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/site/landing.html.erb
<div class="container-fluid span12" id="landing-container">

    <div class="span10" id="landing-title">

      <span style="position: absolute;top: 40%;width: 100%;right: 0%">Regex Challenge</span>
    </div>
    <div class="span4 offset6" style="height: 50%; margin-top: 5%">
      <%= link_to image_tag("github-ruby.png"), 'auth/github', :width => '400px' %>
    </div>
</div>

app/views/users/enter_arena.js.erb
$('#friends_list').html('<%= j render "shared/friends_list" %>');

app/views/users/exit_arena.js.erb
$('#friends_list').html('<%= j render "shared/friends_list" %>');